version: "3.9"

services:

  backend:
    build: ./backend
    container_name: ghostroute-backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: ghostroute-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules